name: Run Writeup Finder with Supabase

on:
  schedule:
    - cron: "0 */3 * * *" # Runs every 3 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  writeup-finder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.5

      - name: Install dependencies
        run: go mod tidy

      - name: Create .env file
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_WORKSPACE/.env
          echo "TELEGRAM_CHANNEL_ID=${{ secrets.TELEGRAM_CHANNEL_ID }}" >> $GITHUB_WORKSPACE/.env
          echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> $GITHUB_WORKSPACE/.env
          echo "MAIN_THREAD_ID=2" >> $GITHUB_WORKSPACE/.env
          echo "PLATFORMS_THREAD_ID=3" >> $GITHUB_WORKSPACE/.env
          echo "TRYHACKME_THREAD_ID=4326" >> $GITHUB_WORKSPACE/.env
          echo "HACKTHEBOX_THREAD_ID=4327" >> $GITHUB_WORKSPACE/.env
          echo "MOBILE_THREAD_ID=4328" >> $GITHUB_WORKSPACE/.env
          echo "MONEY_THREAD_ID=4329" >> $GITHUB_WORKSPACE/.env
          echo "RECON_THREAD_ID=4330" >> $GITHUB_WORKSPACE/.env
          echo "BYPASS_THREAD_ID=4331" >> $GITHUB_WORKSPACE/.env
          echo "PORTSWIGGER_THREAD_ID=4332" >> $GITHUB_WORKSPACE/.env
          echo "BURPSUITE_THREAD_ID=4333" >> $GITHUB_WORKSPACE/.env
          echo "CTF_THREAD_ID=4488" >> $GITHUB_WORKSPACE/.env
          echo "OS_THREAD_ID=4863" >> $GITHUB_WORKSPACE/.env
          echo "VULNERABILITIES_THREAD_ID=4861" >> $GITHUB_WORKSPACE/.env
          echo "TOOLS_THREAD_ID=4865" >> $GITHUB_WORKSPACE/.env
          echo "PROGRAMMINGLANGS_THREAD_ID=4867" >> $GITHUB_WORKSPACE/.env
          echo "CVE_THREAD_ID=5189" >> $GITHUB_WORKSPACE/.env
          echo "OSINT_THREAD_ID=5782" >> $GITHUB_WORKSPACE/.env
          echo "STEGANOGRAPHY_THREAD_ID=9239" >> $GITHUB_WORKSPACE/.env
          echo "WEBSCRAPING_THREAD_ID=9242" >> $GITHUB_WORKSPACE/.env
          echo "CRYPTOGRAPHIC_THREAD_ID=8668" >> $GITHUB_WORKSPACE/.env
          echo "YOUTUBE_THREAD_ID=9400" >> $GITHUB_WORKSPACE/.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_WORKSPACE/.env
          echo "DB_PORT=5432" >> $GITHUB_WORKSPACE/.env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_WORKSPACE/.env
          echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_WORKSPACE/.env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_WORKSPACE/.env

      - name: Run Writeup Finder
        id: run-writeup-finder
        run: |
          set +e
          go run main.go --database --telegram
          if [ $? -ne 0 ]; then
            echo "::set-output name=error_message::Writeup Finder failed with error"
            exit 1
          fi

      - name: Notify Error Alarm Channel
        if: steps.run-writeup-finder.outputs.error_message
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id=${{ secrets.ERROR_ALARM_CHANNEL_ID }} \
          -d text="Error in Writeup Finder: ${{ steps.run-writeup-finder.outputs.error_message }}"
